"""
travel_agent.py

This module creates a simple AI travel assistant using LangChain and Groq.

What this code does:
1. Initializes a Large Language Model (LLM) using the Groq API.
2. Defines a chat prompt template that instructs the model to generate
   a travel itinerary.
3. Accepts a city and a list of user interests as input.
4. Sends the formatted prompt to the language model.
5. Returns a short bulleted travel itinerary for the given city.

Libraries Used:
- langchain_groq.ChatGroq : Connects LangChain with Groq LLM models.
- langchain_core.prompts.ChatPromptTemplate : Helps structure prompts
  using system and human messages.

Inputs:
- city (str): The destination city for the trip.
- interests (list[str]): User interests such as food, museums, beaches, etc.

Output:
- A generated itinerary as a string.
"""

from langchain_groq import ChatGroq
from langchain_core.prompts import ChatPromptTemplate
from src.config.config import GROQ_API_KEY

# Initialize the Groq language model
llm = ChatGroq(
    groq_api_key=GROQ_API_KEY,
    model="llama-3.3-70b-versatile",
    temperature=0.3,
)


# # Define the prompt structure used for generating the itinerary
template_prompt = ChatPromptTemplate(
[
(
"system",
"""
You are a professional travel planner.

Create a detailed **1-day travel itinerary** for {city}.

Traveler Interests:
{interests}

Requirements:

1. The itinerary must follow a **timeline (morning → evening)**.
2. Choose **real famous places in the city**.
3. For each place include:

- Place Name
- Time to visit
- Short description of the place
- Why it matches the user's interests
- Recommended activity to do there

4. Also include:
- A lunch recommendation
- A famous local dish
- A travel tip for the city

5. Format the response in **clean Markdown** using headings and bullet points.

Example format:

# 🌍 One Day Travel Plan for {city}

## ☀️ Morning

### 9:00 AM — Place Name
Description

Why visit:
- reason

Things to do:
- activity

## 🍜 Lunch Recommendation
Restaurant name + dish

## 🌆 Evening

### 5:00 PM — Place Name
 
## 💡 Travel Tip
Helpful advice for visitors.
"""
),
("human","Plan my trip")
]
)



def generate_prompt(city: str, interests: list[str]) -> str:
    """
    Generate a travel itinerary for a given city based on user interests.

    Parameters
    ----------
    city : str
        The city where the user wants to travel.

    interests : list[str]
        A list of user interests (e.g., food, culture, nightlife).

    Returns
    -------
    str
        A text response generated by the Groq LLM containing a
        bulleted travel itinerary.
    """

    response = llm.invoke(
        template_prompt.format_messages(
            city=city,
            interests=", ".join(interests)
        )
    )

    return response.content